services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    command: ["node", "dist/index.js"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./client:/app
    depends_on:
      - server